#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

OMZ_DIR="${ZSH:-$HOME/.oh-my-zsh}"
CUSTOM_DIR="$OMZ_DIR/custom"

ZSHRC="$HOME/.zshrc"
BACKUP_DIR="$HOME/.config/polarzsh/backups"
STATE_FILE="$BACKUP_DIR/install-state.env"
STAMP="$(date +%Y%m%d-%H%M%S)"

die()  { echo "Error: $*" >&2; exit 1; }
info() { echo "[polarzsh] $*"; }

require_arch() {
  [[ -r /etc/arch-release ]] || die "This installer is Arch-only. /etc/arch-release not found."
}

ensure_packages_arch() {
  require_arch

  # What polarzsh expects on Arch
  local pkgs=(
    zsh git curl
    docker docker-compose
    zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search
    fzf zoxide
  )

  info "Ensuring required packages are installed (sudo required)..."
  sudo pacman -Syu --needed "${pkgs[@]}"
}

ensure_omz() {
  if [[ -d "$OMZ_DIR" && -f "$OMZ_DIR/oh-my-zsh.sh" ]]; then
    return 0
  fi

  info "Oh My Zsh not found at '$OMZ_DIR'. Installing unattended..."
  # - RUNZSH=no  => do not start zsh automatically
  # - CHSH=no    => do not change login shell (we keep this manual by default)
  # - KEEP_ZSHRC=yes => do not overwrite existing ~/.zshrc
  RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c \
    "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  [[ -f "$OMZ_DIR/oh-my-zsh.sh" ]] || die "OMZ install failed (missing $OMZ_DIR/oh-my-zsh.sh)."
}

backup_file_if_exists() {
  local path="$1"
  mkdir -p "$BACKUP_DIR"
  if [[ -e "$path" || -L "$path" ]]; then
    local b="$BACKUP_DIR/$(basename "$path").bak.$STAMP"
    cp -a "$path" "$b"
    echo "$b"
  else
    echo ""
  fi
}

link_force() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "$dst")"
  ln -snf "$src" "$dst"
}

main() {
  ensure_packages_arch
  ensure_omz

  mkdir -p "$BACKUP_DIR"
  mkdir -p "$HOME/.config/polarzsh"

  info "Backing up current ~/.zshrc (if present)..."
  ZSHRC_BACKUP="$(backup_file_if_exists "$ZSHRC")"

  info "Installing theme + plugin into OMZ custom directory..."
  link_force "$REPO_DIR/omz/custom/themes/polarzsh.zsh-theme" \
             "$CUSTOM_DIR/themes/polarzsh.zsh-theme"

  mkdir -p "$CUSTOM_DIR/plugins/polarzsh"
  link_force "$REPO_DIR/omz/custom/plugins/polarzsh/polarzsh.plugin.zsh" \
             "$CUSTOM_DIR/plugins/polarzsh/polarzsh.plugin.zsh"

  info "Linking ~/.zshrc to repo-managed minimal config..."
  link_force "$REPO_DIR/files/zshrc.minimal" "$ZSHRC"

  info "Writing install state for clean uninstall..."
  cat > "$STATE_FILE" <<STATE
# Generated by polarzsh install.sh
OMZ_DIR="$OMZ_DIR"
CUSTOM_DIR="$CUSTOM_DIR"
ZSHRC="$ZSHRC"
ZSHRC_BACKUP="$ZSHRC_BACKUP"
THEME_LINK="$CUSTOM_DIR/themes/polarzsh.zsh-theme"
PLUGIN_LINK="$CUSTOM_DIR/plugins/polarzsh/polarzsh.plugin.zsh"
STATE

  info "Done. Start zsh with: exec zsh"
  info "If you want zsh as default login shell: chsh -s /usr/bin/zsh"
}

main "$@"
